// ============================================================
// Glossary terms — used by both the interactive hover system
// and the end-of-document glossary page.
// ============================================================
window.GLOSSARY = [
  // Core Lorwyn/Shadowmoor terms
  { term: "Aurora", also: ["Great Aurora"], def: "The recurring turning of Lorwyn into Shadowmoor and back — a natural cycle of the plane that Oona stretched so each phase lasted centuries. The Great Aurora is the one that came a century early, while the tribes were unprepared." },
  { term: "Blessed Nation", def: "The collective elf civilization, organized by caste. Ruled by the High Perfects of the Gilt Leaf." },
  { term: "Cenn", def: "The kithkin equivalent of a mayor or chief — the clachan's leader, anchor of the thoughtweft." },
  { term: "Cervin", def: "The elegant deer-like mounts of the elf nobility. Certain bloodlines are reserved for high caste." },
  { term: "Cinder", def: "The Shadowmoor form of flamekin — half-dead coal and ash creatures, living embodiments of destruction." },
  { term: "Clachan", def: "A Lorwyn kithkin fortified village-town. Warm and communal." },
  { term: "Clique", def: "Three or more faeries bonded for life — commonly a pair of twins and one odd sibling out, usually of a single sex. Members share an empathic link that becomes telepathy under stress." },
  { term: "Crannog", def: "A merrow village at the river's edge, extending far below the waterline — a small dock above may conceal ten times its population below." },
  { term: "Daen", def: "Commander of an elf hunting pack." },
  { term: "Doun", def: "A Shadowmoor kithkin fortified village. Paranoid, defensive, ever-watchful." },
  { term: "Dreamstuff", def: "Tangible thoughts and dreams, visible only to fae. Harvested for Oona — the fuel, it turns out, of the Aurora itself." },
  { term: "Eyeblight", def: "An elf stripped of caste status through disfigurement, deformity, or disgrace. Considered lower than a boggart." },
  { term: "Gilt Leaf", def: "The greatest elf tribe, masters of the Gilt Leaf Wood. Its hunters enforce elven order across Lorwyn." },
  { term: "Glamer", def: "Illusion magic — used by faeries for concealment and by merrow to modulate their appearance and voice for landwalkers." },
  { term: "Glen Elendra", def: "Oona's hidden home, concealed by glamers so strong that non-fae who approach simply forget why they came." },
  { term: "Lanamnas", def: "A kithkin concept: any unequal relationship bound together by mutual obligation rather than raw power." },
  { term: "Mindweft", also: ["Thoughtweft"], def: "The kithkin psychic bond connecting an entire village. Warm and communal in Lorwyn; paranoid and defensive in Shadowmoor." },
  { term: "Moonglove", def: "The flowering plant that is the source of elf poison and the philosophy that beauty conceals lethality." },
  { term: "Oona", def: "Queen of the Fae. Ancient, vast, and the architect of the stretched Aurora cycle. Killed at the Heart of Glen Elendra by Rhys's yew poison, Ashling's fire, and Maralen's moonglove." },
  { term: "Perfect", def: "The highest caste of the Blessed Nation. The most beautiful and powerful elves." },
  { term: "Pilgrim", def: "A flamekin on the Path — a lifetime spiritual journey to find and commune with their elemental spirit." },
  { term: "Shapewater", def: "Merrow magic that forms water into solid, navigable structures." },
  { term: "Springjack", def: "The large horned rabbit-like mounts and pack animals of the kithkin." },
  { term: "Taercenn", def: "The highest elf military rank — supreme commander over multiple packs." },
  { term: "Vendilion Clique", def: "Iliona, Veesa, and Endry — three faerie siblings bonded for life. Spies, guides, and reluctant allies throughout the cycle." },
  { term: "Vinebred", def: "Living creatures altered and controlled through nettlevine implants. Elf shock troops — and, in elf eyes, works of art." },
  { term: "Wilt-Leaf", def: "The Shadowmoor elves — the closest thing the dark plane has to good guys. They find and protect whatever scraps of beauty remain, ruled by a king and queen from Cayr Ulios and living in fortified safeholds." },
  { term: "Scarblade", def: "A specialized elf assassin trained to maim rather than kill — disfigurement, to elves, is a worse fate than death." },

  // Eclipsed terms
  { term: "Bloomseeker", def: "A near-religious Shadowmoor elf who studies the beauty of Lorwyn — one of the few permitted to carry a Reliquary of Twilight." },
  { term: "Calciform", def: "Our name for a creature calcified by prolonged exposure to an eclipsed realm — dual memories cancel, leaving an empty husk. The calcification and the husks are sourced; the word is ours." },
  { term: "Dawnglow", also: ["Dawnglove"], def: "Shadowmoor's mirror of moonglove. Distilled into dawnglow, it can cure nearly any ailment — including death itself." },
  { term: "Eclipsed Realm", def: "A third state between Lorwyn and Shadowmoor where both sun and moon hang motionless. Strange, disorienting, and ultimately fatal." },
  { term: "Eirdu", def: "The day worldsoul: six-legged, winged, long-tailed, a sun hovering above its head. Where it walks, Lorwyn's daylight returns. Referred to as 'it.'" },
  { term: "Isilu", def: "The night worldsoul: six-legged, winged, a moon on its head, wings that furrow the soil and leave moonflowers. Usually sleeping. Referred to as 'it.'" },
  { term: "Firdoch", def: "Stone creatures that appeared with Eirdu and Isilu, carving and wrestling boundaries between the aspects." },
  { term: "Flicker", def: "A flamekin settlement — small, impermanent, nomadic by nature." },
  { term: "Inneal ionnsaigh", def: "The boggart term for the Phyrexian Invasion. Translates as 'the metal invasion.'" },
  { term: "Inslintur", def: "Towers in Shadowmoor douns where the monthly-elected Sul is locked in to watch for threats." },
  { term: "Name Sleep", def: "The deep slumber a giant enters on sudden trauma or sudden abundance. Giants derive surnames from what they dream there." },
  { term: "Pendulum Year", def: "The chaotic period immediately after Oona's defeat, when Lorwyn and Shadowmoor began to bleed into each other." },
  { term: "Reliquary", def: "Rare artifacts made of Eirdu or Isilu's bodies. Let the bearer cross an aurora without transforming." },
  { term: "Exquisite", def: "The second-highest elf caste: taercenns, courtiers, artists, spiritual leaders. Below Perfect; above Immaculate and Faultless." },
  { term: "Faultless", def: "The lowest and most populous elf caste — the minimum threshold of beauty for acceptance in the Blessed Nation." },
  { term: "Winnower", def: "Elf hunters specially trained to hunt down and eliminate eyeblights." },
  { term: "Safehold", def: "A fortified Wilt-Leaf refuge in Shadowmoor, kept by officers called safewrights." },
  { term: "Porringer Valley", def: "Site of the botched boggart extermination where Rhys's yew blast killed most of three Gilt Leaf packs and destroyed his horns." },
  { term: "Mistmeadow", def: "The Shadowmoor doun Brigid defends against the Destroyer at the opening of Eventide." },
  { term: "Rimekin", def: "What flamekin become — and are called — when the plane turns to Shadowmoor: their fire goes blue-white and frozen. Ashling: \'By night, I\'m what we call rimekin.\' The Planeswalker\'s Guide also describes flamekin whose fire turned permanently inward under the trauma of the Phyrexian Invasion." },
  { term: "Wild Magic", def: "Chaotic power inherent to Shadowmoor's land. Anyone can draw on it; any use risks catastrophic backlash." },

  // Characters
  { term: "Rhys", def: "Daen of the Hemlock Pack (~100 hunters), disgraced when the yew magic he called on in Porringer Valley destroyed his horns and most of three Gilt Leaf packs. In Shadowmoor: Second Safewright Rhys of the Wilt-Leaf, with no memory of exile until Oona dies. In the Eclipsed era: Rhys the Evermore, bound to Maralen, carrying the moonglove she handed him." },
  { term: "Maralen", def: "Oona's vessel, built on the body of a murdered Mornsong elf — Maralen the Exquisite, maid-in-waiting to Perfect Peradala — a century before the early Aurora was due. Developed a will of her own, led a fae rebellion, and killed Oona with the dead elf's own moonglove. Queen of the Fae by Eventide's end." },
  { term: "Ashling", def: "A flamekin pilgrim whose quest for her elemental consumes the cycle. Merges with it at the Aurora and becomes the Destroyer — whom the cinders call their Extinguisher. Loses the elemental at Oona's death. Nearly forty years later, back from the Primal Beyond as Ashling, Rekindled — and, by night, a blue-burning rimekin." },
  { term: "Colfenor", def: "The great red yew, thought to be the only yew treefolk on Lorwyn. An ancient sage who felt the Aurora coming and arranged Rhys, Ashling, Brigid, and Gaddock Teeg to his own ends. Dies at the climax of the first novel, burning himself in Ashling's fire so his seed would awaken anew." },
  { term: "Sygg", def: "A rudder — a merrow ferryman — who pilots a shapewater ferry along the Lanes, with a knack for knowing exactly when an offer has become acceptable." },
  { term: "Brigid Baeli", def: "Hero of Kinsbaile, kithkin archer and Gaddock Teeg's right hand. Betrayed her companions on Colfenor's orders in Lorwyn and spent Morningtide seeking redemption. Took the Crescent of Morningtide from Sygg at the Source — and because she held it when the Aurora struck, she alone among kithkin remembered Lorwyn." },
  { term: "Rosheen Meanderer", def: "The oracular giantess who sleeps in a valley, muttering prophecy. Her cloudgoat Mr. Choppers grazes among the clouds." },
  { term: "Oko", def: "Oona's first avatar, created to enact her will when the plane turned to Shadowmoor. His Lorwyn side rebelled; he sparked and left the plane. Present on Lorwyn again in the Eclipsed story." },
];
